#include "info.h"

const char info[] =
    "Usage:\n"
    "  cltext <file.clt>\n"
    "  cltext [options]\n"
    "\n"
    "Tags:\n"
    "  basic:\n"
    "    bold             makes text bold:     <bold>text</bold>\n"
    "    tilt             makes text italic:   <tilt>text</tilt>\n"
    "    small            makes text small:    <small>text</small>\n"
    "    big              makes text big:      <big>text</big>\n"
    "    reverse          makes text reversed: <reverse>text</reverse>\n"
    "    color            makes text a color:  <color c=\"#000000\">text</color>\n\n"
    "  Animated:\n"
    "    wave             makes text wavy:     <wave a=1>text</wave>\n"
    "    bounce           makes text bounce:   <bounce a=1>text</bounce>\n"
    "    shake            makes text shaky:    <shake a=1>text</shake>\n"
    "    glitch           makes text glitchy:  <glitch>text</glitch>\n\n"
    "  Document:\n"
    "    bgcolor          changes bg color:    <bgcolor c=\"#000000\">\n"
    "    txtcolor         changes text color:  <txtcolor c=\"#000000\">\n"
    "    title            changes window title:<title name=\"title\">\n\n"
    "Comments:\n"
    "  <?== comment ==?>\n\n"
    "Options:\n"
    "  -h, --help                  Show this help message\n"
    "  -v, --version               Show the Cltext version\n"
    "    -v extension, -v cltext   Show specified version\n";